server:
  port: 8888

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/sall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
#thymeleaf配置
  thymeleaf:
    #开启模板缓存（默认值：true）
    cache: false
    #Check that the template exists before rendering it.
    check-template: true
    #检查模板位置是否正确（默认值:true）
    check-template-location: true
    #Content-Type的值（默认值：text/html）
    content-type: text/html
    #开启MVC Thymeleaf视图解析（默认值：true）
    enabled: true
    #模板编码
    encoding: UTF-8
    #要被排除在解析之外的视图名称列表，用逗号分隔
#    excluded-view-names:
    #要运用于模板之上的模板模式。另见StandardTemplate-ModeHandlers(默认值：HTML5)
    mode: HTML5
    #在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）
    prefix: classpath:/templates/
    #在构建URL时添加到视图名称后的后缀（默认值：.html）
    suffix: .html
    #Thymeleaf模板解析器在解析器链中的顺序。默认情况下，它排第一位。顺序从1开始，只有在定义了额外的TemplateResolver Bean时才需要设置这个属性。
#    template-resolver-order:
    #可解析的视图名称列表，用逗号分隔
#    view-names:
  #  redis缓存
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
    timeout: 0
    password:


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.sall.mapper

#showSql
logging:
  level:
    com:
      example:
        sall:
          mapper : debug